package LamportApp;


/**
* LamportApp/LamportInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LamportApp.idl
* Wednesday, June 15, 2016 8:36:18 PM CEST
*/

public interface LamportInt extends LamportIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LamportInt
