package LamportApp;


/**
* LamportApp/LamportIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LamportApp.idl
* Wednesday, June 15, 2016 8:36:18 PM CEST
*/

public interface LamportIntOperations 
{
  int receive (int time);
  void shutdown ();
} // interface LamportIntOperations
