package LamportApp;

/**
* LamportApp/LamportIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LamportApp.idl
* Wednesday, June 15, 2016 8:36:18 PM CEST
*/

public final class LamportIntHolder implements org.omg.CORBA.portable.Streamable
{
  public LamportApp.LamportInt value = null;

  public LamportIntHolder ()
  {
  }

  public LamportIntHolder (LamportApp.LamportInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LamportApp.LamportIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LamportApp.LamportIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LamportApp.LamportIntHelper.type ();
  }

}
